# Generated by Django 4.1 on 2022-08-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="profile_img", new_name="profileimg",
        ),
    ]
