# Generated by Django 4.1 on 2022-08-27 15:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_profile_img_profile_profileimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("user", models.CharField(max_length=100)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
