# Generated by Django 4.1 on 2022-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_profile_name_remove_profile_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="surname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
